import { NextResponse } from "next/server";

export async function GET(
    req: Request,
    { params }: { params: { id: string } }
) {
    const { id } = params;

    type NosologyDoctor = {
        id: string;
        name: string;
        diagnosesCount: number;
        requiredServices: number;
        assignPercent: number;
        completionPercent: number;
        deviationPercent: number;
        revenue: string;
        lostRevenue: string;
        avgAssign: number;
    };

    const doctorsByNosology: Record<string, NosologyDoctor[]> = {
        "1": [
            {
                id: "4",
                name: "Смирнов Д.О.",
                diagnosesCount: 62,
                requiredServices: 19,
                assignPercent: 91,
                completionPercent: 86,
                deviationPercent: 7,
                revenue: "167 400 ₽",
                lostRevenue: "9 600 ₽",
                avgAssign: 3.1,
            },
            {
                id: "3",
                name: "Сидоров М.К.",
                diagnosesCount: 74,
                requiredServices: 22,
                assignPercent: 93,
                completionPercent: 88,
                deviationPercent: 6,
                revenue: "214 600 ₽",
                lostRevenue: "10 400 ₽",
                avgAssign: 3.2,
            },
            {
                id: "2",
                name: "Петров И.В.",
                diagnosesCount: 49,
                requiredServices: 15,
                assignPercent: 92,
                completionPercent: 87,
                deviationPercent: 6,
                revenue: "132 300 ₽",
                lostRevenue: "8 200 ₽",
                avgAssign: 3,
            },
            {
                id: "1",
                name: "Иванов А.А.",
                diagnosesCount: 49,
                requiredServices: 15,
                assignPercent: 92,
                completionPercent: 87,
                deviationPercent: 6,
                revenue: "132 300 ₽",
                lostRevenue: "8 200 ₽",
                avgAssign: 3,
            },
            {
                id: "10",
                name: "Морозов Л.Г.",
                diagnosesCount: 49,
                requiredServices: 15,
                assignPercent: 92,
                completionPercent: 87,
                deviationPercent: 6,
                revenue: "132 300 ₽",
                lostRevenue: "8 200 ₽",
                avgAssign: 3,
            },
            {
                id: "9",
                name: "Фёдоров С.В.",
                diagnosesCount: 49,
                requiredServices: 15,
                assignPercent: 92,
                completionPercent: 87,
                deviationPercent: 6,
                revenue: "132 300 ₽",
                lostRevenue: "8 200 ₽",
                avgAssign: 3,
            },
            {
                id: "8",
                name: "Новиков П.А.",
                diagnosesCount: 49,
                requiredServices: 15,
                assignPercent: 92,
                completionPercent: 87,
                deviationPercent: 6,
                revenue: "132 300 ₽",
                lostRevenue: "8 200 ₽",
                avgAssign: 3,
            },
            {
                id: "7",
                name: "Васильев Е.Д.",
                diagnosesCount: 49,
                requiredServices: 15,
                assignPercent: 92,
                completionPercent: 87,
                deviationPercent: 6,
                revenue: "132 300 ₽",
                lostRevenue: "8 200 ₽",
                avgAssign: 3,
            },
            {
                id: "6",
                name: "Попов Н.И.",
                diagnosesCount: 49,
                requiredServices: 15,
                assignPercent: 92,
                completionPercent: 87,
                deviationPercent: 6,
                revenue: "132 300 ₽",
                lostRevenue: "8 200 ₽",
                avgAssign: 3,
            },
            {
                id: "5",
                name: "Кузнецов Р.С.",
                diagnosesCount: 49,
                requiredServices: 15,
                assignPercent: 92,
                completionPercent: 87,
                deviationPercent: 6,
                revenue: "132 300 ₽",
                lostRevenue: "8 200 ₽",
                avgAssign: 3,
            },
        ],
        "4": [
            {
                id: "1",
                name: "Иванов А.А.",
                diagnosesCount: 85,
                requiredServices: 15,
                assignPercent: 85,
                completionPercent: 93,
                deviationPercent: 44.5,
                revenue: "319 000 ₽",
                lostRevenue: "155 000 ₽",
                avgAssign: 6.5,
            },
            {
                id: "2",
                name: "Петров И.В.",
                diagnosesCount: 78,
                requiredServices: 15,
                assignPercent: 83,
                completionPercent: 91,
                deviationPercent: 49.6,
                revenue: "295 500 ₽",
                lostRevenue: "147 000 ₽",
                avgAssign: 6.4,
            },
            {
                id: "3",
                name: "Сидоров М.К.",
                diagnosesCount: 72,
                requiredServices: 22,
                assignPercent: 68,
                completionPercent: 70,
                deviationPercent: 52.4,
                revenue: "280 000 ₽",
                lostRevenue: "140 500 ₽",
                avgAssign: 6.3,
            },
            {
                id: "4",
                name: "Смирнов Д.О.",
                diagnosesCount: 70,
                requiredServices: 53,
                assignPercent: 53,
                completionPercent: 61,
                deviationPercent: 67.7,
                revenue: "242 000 ₽",
                lostRevenue: "145 000 ₽",
                avgAssign: 4.8,
            },
            {
                id: "5",
                name: "Кузнецов Р.С.",
                diagnosesCount: 68,
                requiredServices: 15,
                assignPercent: 65,
                completionPercent: 68,
                deviationPercent: 55.8,
                revenue: "268 500 ₽",
                lostRevenue: "137 000 ₽",
                avgAssign: 6.2,
            },
            {
                id: "6",
                name: "Попов Н.И.",
                diagnosesCount: 65,
                requiredServices: 15,
                assignPercent: 60,
                completionPercent: 65,
                deviationPercent: 61,
                revenue: "255 000 ₽",
                lostRevenue: "138 500 ₽",
                avgAssign: 6.1,
            },
            {
                id: "7",
                name: "Васильев Е.Д.",
                diagnosesCount: 63,
                requiredServices: 15,
                assignPercent: 58,
                completionPercent: 63,
                deviationPercent: 63.5,
                revenue: "248 500 ₽",
                lostRevenue: "140 000 ₽",
                avgAssign: 6,
            },
            {
                id: "8",
                name: "Новиков П.А.",
                diagnosesCount: 60,
                requiredServices: 15,
                assignPercent: 62,
                completionPercent: 66,
                deviationPercent: 59.1,
                revenue: "240 000 ₽",
                lostRevenue: "136 000 ₽",
                avgAssign: 6.1,
            },
            {
                id: "9",
                name: "Фёдоров С.В.",
                diagnosesCount: 53,
                requiredServices: 15,
                assignPercent: 57,
                completionPercent: 64,
                deviationPercent: 63.5,
                revenue: "212 500 ₽",
                lostRevenue: "128 000 ₽",
                avgAssign: 6,
            },
            {
                id: "10",
                name: "Морозов Л.Г.",
                diagnosesCount: 50,
                requiredServices: 15,
                assignPercent: 55,
                completionPercent: 61,
                deviationPercent: 66,
                revenue: "200 000 ₽",
                lostRevenue: "126 500 ₽",
                avgAssign: 5.9,
            },
        ],
        "5": [
            {
                id: "11",
                name: "Волков А.Н.",
                diagnosesCount: 58,
                requiredServices: 18,
                assignPercent: 96,
                completionPercent: 90,
                deviationPercent: 4,
                revenue: "191 100 ₽",
                lostRevenue: "7 900 ₽",
                avgAssign: 3.3,
            },
            {
                id: "12",
                name: "Алексеев Д.П.",
                diagnosesCount: 79,
                requiredServices: 24,
                assignPercent: 94,
                completionPercent: 88,
                deviationPercent: 5,
                revenue: "257 400 ₽",
                lostRevenue: "11 600 ₽",
                avgAssign: 3.4,
            },
            {
                id: "13",
                name: "Лебедев И.С.",
                diagnosesCount: 67,
                requiredServices: 20,
                assignPercent: 93,
                completionPercent: 87,
                deviationPercent: 6,
                revenue: "214 500 ₽",
                lostRevenue: "8 500 ₽",
                avgAssign: 3.2,
            },
            {
                id: "14",
                name: "Семёнов К.М.",
                diagnosesCount: 58,
                requiredServices: 18,
                assignPercent: 96,
                completionPercent: 90,
                deviationPercent: 4,
                revenue: "191 100 ₽",
                lostRevenue: "7 900 ₽",
                avgAssign: 3.3,
            },
            {
                id: "15",
                name: "Егоров В.Т.",
                diagnosesCount: 79,
                requiredServices: 24,
                assignPercent: 94,
                completionPercent: 88,
                deviationPercent: 5,
                revenue: "257 400 ₽",
                lostRevenue: "11 600 ₽",
                avgAssign: 3.4,
            },
            {
                id: "16",
                name: "Павлов Р.А.",
                diagnosesCount: 67,
                requiredServices: 20,
                assignPercent: 93,
                completionPercent: 87,
                deviationPercent: 6,
                revenue: "214 500 ₽",
                lostRevenue: "8 500 ₽",
                avgAssign: 3.2,
            },
            {
                id: "17",
                name: "Козлов О.В.",
                diagnosesCount: 58,
                requiredServices: 18,
                assignPercent: 96,
                completionPercent: 90,
                deviationPercent: 4,
                revenue: "191 100 ₽",
                lostRevenue: "7 900 ₽",
                avgAssign: 3.3,
            },
            {
                id: "18",
                name: "Степанов М.Е.",
                diagnosesCount: 79,
                requiredServices: 24,
                assignPercent: 94,
                completionPercent: 88,
                deviationPercent: 5,
                revenue: "257 400 ₽",
                lostRevenue: "11 600 ₽",
                avgAssign: 3.4,
            },
            {
                id: "19",
                name: "Никитин С.П.",
                diagnosesCount: 67,
                requiredServices: 20,
                assignPercent: 93,
                completionPercent: 87,
                deviationPercent: 6,
                revenue: "214 500 ₽",
                lostRevenue: "8 500 ₽",
                avgAssign: 3.2,
            },
            {
                id: "20",
                name: "Захаров Д.И.",
                diagnosesCount: 67,
                requiredServices: 20,
                assignPercent: 93,
                completionPercent: 87,
                deviationPercent: 6,
                revenue: "214 500 ₽",
                lostRevenue: "8 500 ₽",
                avgAssign: 3.2,
            },
        ],
        "3": [
            {
                id: "4",
                name: "Кузнецов Д.В.",
                diagnosesCount: 56,
                requiredServices: 17,
                assignPercent: 92,
                completionPercent: 84,
                deviationPercent: 8,
                revenue: "173 600 ₽",
                lostRevenue: "9 400 ₽",
                avgAssign: 3.1,
            },
            {
                id: "6",
                name: "Фёдоров С.А.",
                diagnosesCount: 70,
                requiredServices: 21,
                assignPercent: 90,
                completionPercent: 83,
                deviationPercent: 9,
                revenue: "210 100 ₽",
                lostRevenue: "12 900 ₽",
                avgAssign: 3.1,
            },
            {
                id: "9",
                name: "Орлова В.С.",
                diagnosesCount: 52,
                requiredServices: 16,
                assignPercent: 91,
                completionPercent: 85,
                deviationPercent: 7,
                revenue: "150 300 ₽",
                lostRevenue: "11 700 ₽",
                avgAssign: 3,
            },
        ],
        "11": [
            {
                id: "31",
                name: "Петров П.П.",
                diagnosesCount: 44,
                requiredServices: 14,
                assignPercent: 95,
                completionPercent: 89,
                deviationPercent: 5,
                revenue: "140 600 ₽",
                lostRevenue: "6 400 ₽",
                avgAssign: 3.2,
            },
            {
                id: "32",
                name: "Савельев Д.А.",
                diagnosesCount: 37,
                requiredServices: 12,
                assignPercent: 96,
                completionPercent: 90,
                deviationPercent: 4,
                revenue: "118 400 ₽",
                lostRevenue: "5 600 ₽",
                avgAssign: 3.2,
            },
            {
                id: "33",
                name: "Мельников И.О.",
                diagnosesCount: 41,
                requiredServices: 13,
                assignPercent: 94,
                completionPercent: 88,
                deviationPercent: 5,
                revenue: "132 900 ₽",
                lostRevenue: "7 100 ₽",
                avgAssign: 3.2,
            },
            {
                id: "34",
                name: "Щербаков К.В.",
                diagnosesCount: 44,
                requiredServices: 14,
                assignPercent: 95,
                completionPercent: 89,
                deviationPercent: 5,
                revenue: "140 600 ₽",
                lostRevenue: "6 400 ₽",
                avgAssign: 3.2,
            },
            {
                id: "35",
                name: "Калинин Р.Д.",
                diagnosesCount: 37,
                requiredServices: 12,
                assignPercent: 96,
                completionPercent: 90,
                deviationPercent: 4,
                revenue: "118 400 ₽",
                lostRevenue: "5 600 ₽",
                avgAssign: 3.2,
            },
            {
                id: "36",
                name: "Зайцев П.С.",
                diagnosesCount: 41,
                requiredServices: 13,
                assignPercent: 94,
                completionPercent: 88,
                deviationPercent: 5,
                revenue: "132 900 ₽",
                lostRevenue: "7 100 ₽",
                avgAssign: 3.2,
            },
            {
                id: "37",
                name: "Титов М.А.",
                diagnosesCount: 44,
                requiredServices: 14,
                assignPercent: 95,
                completionPercent: 89,
                deviationPercent: 5,
                revenue: "140 600 ₽",
                lostRevenue: "6 400 ₽",
                avgAssign: 3.2,
            },
            {
                id: "38",
                name: "Виноградов Е.И.",
                diagnosesCount: 37,
                requiredServices: 12,
                assignPercent: 96,
                completionPercent: 90,
                deviationPercent: 4,
                revenue: "118 400 ₽",
                lostRevenue: "5 600 ₽",
                avgAssign: 3.2,
            },
            {
                id: "39",
                name: "Королёв С.Д.",
                diagnosesCount: 41,
                requiredServices: 13,
                assignPercent: 94,
                completionPercent: 88,
                deviationPercent: 5,
                revenue: "132 900 ₽",
                lostRevenue: "7 100 ₽",
                avgAssign: 3.2,
            },
            {
                id: "40",
                name: "Ильин О.П.",
                diagnosesCount: 41,
                requiredServices: 13,
                assignPercent: 94,
                completionPercent: 88,
                deviationPercent: 5,
                revenue: "132 900 ₽",
                lostRevenue: "7 100 ₽",
                avgAssign: 3.2,
            },
        ],
        "8": [
            {
                id: "21",
                name: "Макаров А.С.",
                diagnosesCount: 39,
                requiredServices: 12,
                assignPercent: 91,
                completionPercent: 84,
                deviationPercent: 8,
                revenue: "113 100 ₽",
                lostRevenue: "6 900 ₽",
                avgAssign: 3,
            },
            {
                id: "22",
                name: "Андреев И.Н.",
                diagnosesCount: 48,
                requiredServices: 15,
                assignPercent: 89,
                completionPercent: 82,
                deviationPercent: 10,
                revenue: "139 200 ₽",
                lostRevenue: "8 800 ₽",
                avgAssign: 3,
            },
            {
                id: "23",
                name: "Тарасов В.О.",
                diagnosesCount: 36,
                requiredServices: 10,
                assignPercent: 90,
                completionPercent: 83,
                deviationPercent: 9,
                revenue: "104 700 ₽",
                lostRevenue: "8 300 ₽",
                avgAssign: 2.9,
            },
            {
                id: "24",
                name: "Беляев К.Д.",
                diagnosesCount: 39,
                requiredServices: 12,
                assignPercent: 91,
                completionPercent: 84,
                deviationPercent: 8,
                revenue: "113 100 ₽",
                lostRevenue: "6 900 ₽",
                avgAssign: 3,
            },
            {
                id: "25",
                name: "Комаров П.В.",
                diagnosesCount: 48,
                requiredServices: 15,
                assignPercent: 89,
                completionPercent: 82,
                deviationPercent: 10,
                revenue: "139 200 ₽",
                lostRevenue: "8 800 ₽",
                avgAssign: 3,
            },
            {
                id: "26",
                name: "Орлов Р.М.",
                diagnosesCount: 36,
                requiredServices: 10,
                assignPercent: 90,
                completionPercent: 83,
                deviationPercent: 9,
                revenue: "104 700 ₽",
                lostRevenue: "8 300 ₽",
                avgAssign: 2.9,
            },
            {
                id: "27",
                name: "Киселёв С.А.",
                diagnosesCount: 39,
                requiredServices: 12,
                assignPercent: 91,
                completionPercent: 84,
                deviationPercent: 8,
                revenue: "113 100 ₽",
                lostRevenue: "6 900 ₽",
                avgAssign: 3,
            },
            {
                id: "28",
                name: "Громов Д.С.",
                diagnosesCount: 48,
                requiredServices: 15,
                assignPercent: 89,
                completionPercent: 82,
                deviationPercent: 10,
                revenue: "139 200 ₽",
                lostRevenue: "8 800 ₽",
                avgAssign: 3,
            },
            {
                id: "29",
                name: "Денисов И.К.",
                diagnosesCount: 36,
                requiredServices: 10,
                assignPercent: 90,
                completionPercent: 83,
                deviationPercent: 9,
                revenue: "104 700 ₽",
                lostRevenue: "8 300 ₽",
                avgAssign: 2.9,
            },
            {
                id: "30",
                name: "Григорьев А.В.",
                diagnosesCount: 36,
                requiredServices: 10,
                assignPercent: 90,
                completionPercent: 83,
                deviationPercent: 9,
                revenue: "104 700 ₽",
                lostRevenue: "8 300 ₽",
                avgAssign: 2.9,
            },
        ],
    };

    const doctors = doctorsByNosology[id] || [];
    return NextResponse.json(doctors);
}
