import { NextResponse } from "next/server";

const doctors = [
    {
        id: "1",
        fullName: "Иванов И.И.",
        profession: "Терапевт",
        appointments: 120,
        primary: 45,
        requiredKR: 30,
        deviationPercent: 5,
        totalServices: 400,
        avgServicesPerVisit: 3.3,
        noServices: "8% (10)",
        avgBill: "2 300 ₽",
        revenue: "276 000 ₽",
        servicesPerVisit: 3.3,
    },
    {
        id: "2",
        fullName: "Петров П.П.",
        profession: "Кардиолог",
        appointments: 95,
        primary: 30,
        requiredKR: 28,
        deviationPercent: 3,
        totalServices: 310,
        avgServicesPerVisit: 3.2,
        noServices: "5% (5)",
        avgBill: "2 600 ₽",
        revenue: "247 000 ₽",
        servicesPerVisit: 3.2,
    },
    {
        id: "3",
        fullName: "Сидорова А.А.",
        profession: "Терапевт",
        appointments: 130,
        primary: 60,
        requiredKR: 35,
        deviationPercent: 4,
        totalServices: 450,
        avgServicesPerVisit: 3.5,
        noServices: "6% (8)",
        avgBill: "2 100 ₽",
        revenue: "273 000 ₽",
        servicesPerVisit: 3.5,
    },
    {
        id: "4",
        fullName: "Кузнецов Д.В.",
        profession: "Эндокринолог",
        appointments: 80,
        primary: 25,
        requiredKR: 20,
        deviationPercent: 2,
        totalServices: 290,
        avgServicesPerVisit: 3.6,
        noServices: "4% (3)",
        avgBill: "3 200 ₽",
        revenue: "256 000 ₽",
        servicesPerVisit: 3.6,
    },
    {
        id: "5",
        fullName: "Морозова Е.Н.",
        profession: "Кардиолог",
        appointments: 110,
        primary: 40,
        requiredKR: 33,
        deviationPercent: 6,
        totalServices: 370,
        avgServicesPerVisit: 3.4,
        noServices: "7% (8)",
        avgBill: "2 800 ₽",
        revenue: "308 000 ₽",
        servicesPerVisit: 3.4,
    },
    {
        id: "6",
        fullName: "Фёдоров С.А.",
        profession: "Эндокринолог",
        appointments: 105,
        primary: 38,
        requiredKR: 31,
        deviationPercent: 3,
        totalServices: 350,
        avgServicesPerVisit: 3.3,
        noServices: "5% (6)",
        avgBill: "2 700 ₽",
        revenue: "283 000 ₽",
        servicesPerVisit: 3.3,
    },
    {
        id: "7",
        fullName: "Васильева М.Г.",
        profession: "Кардиолог",
        appointments: 90,
        primary: 28,
        requiredKR: 27,
        deviationPercent: 2,
        totalServices: 310,
        avgServicesPerVisit: 3.4,
        noServices: "6% (5)",
        avgBill: "2 900 ₽",
        revenue: "261 000 ₽",
        servicesPerVisit: 3.4,
    },
    {
        id: "8",
        fullName: "Григорьев Л.Т.",
        profession: "Терапевт",
        appointments: 85,
        primary: 25,
        requiredKR: 22,
        deviationPercent: 1,
        totalServices: 300,
        avgServicesPerVisit: 3.5,
        noServices: "3% (2)",
        avgBill: "3 000 ₽",
        revenue: "255 000 ₽",
        servicesPerVisit: 3.5,
    },
    {
        id: "9",
        fullName: "Орлова В.С.",
        profession: "Эндокринолог",
        appointments: 100,
        primary: 32,
        requiredKR: 30,
        deviationPercent: 3,
        totalServices: 340,
        avgServicesPerVisit: 3.4,
        noServices: "5% (5)",
        avgBill: "2 750 ₽",
        revenue: "275 000 ₽",
        servicesPerVisit: 3.4,
    },
    {
        id: "10",
        fullName: "Николаев Р.И.",
        profession: "Кардиолог",
        appointments: 92,
        primary: 29,
        requiredKR: 26,
        deviationPercent: 4,
        totalServices: 320,
        avgServicesPerVisit: 3.3,
        noServices: "6% (6)",
        avgBill: "2 850 ₽",
        revenue: "263 000 ₽",
        servicesPerVisit: 3.3,
    },
];

export async function GET() {
    return NextResponse.json(doctors);
}
