import { NextResponse } from "next/server";
import type { Doctor } from "@/components/DoctorsTable/DoctorsTable";

const doctors: Doctor[] = [
    {
        id: "1",
        fullName: "Иванов А.А.",
        profession: "Терапевт",
        appointments: 118,
        primary: 46,
        repeatAppointments: 72,
        requiredKR: 31,
        krServicesDone: 28,
        deviationPercent: 9,
        totalServices: 356,
        avgServicesPerVisit: 3,
        servicesPerVisit: 3,
        noServices: "8% (9)",
        assignedOUKRAvg: 90,
        servicesCompletedPercent: 81,
            overKR: 2,
        avgBill: "2 750 ₽",
        revenue: "324 500 ₽",
        potentialRevenue: "346 000 ₽",
        lostOUKRRevenue: "21 500 ₽",
        lostOUKRPercent: 7,
    },
    {
        id: "2",
        fullName: "Петров И.В.",
        profession: "Терапевт",
        appointments: 96,
        primary: 34,
        repeatAppointments: 62,
        requiredKR: 29,
        krServicesDone: 28,
        deviationPercent: 4,
        totalServices: 316,
        avgServicesPerVisit: 3.3,
        servicesPerVisit: 3.3,
        noServices: "5% (5)",
        assignedOUKRAvg: 97,
        servicesCompletedPercent: 82,
            overKR: 1,
        avgBill: "3 250 ₽",
        revenue: "312 000 ₽",
        potentialRevenue: "324 000 ₽",
        lostOUKRRevenue: "12 000 ₽",
        lostOUKRPercent: 4,
    },
    {
        id: "3",
        fullName: "Сидоров М.К.",
        profession: "Терапевт",
        appointments: 132,
        primary: 52,
        repeatAppointments: 80,
        requiredKR: 35,
        krServicesDone: 33,
        deviationPercent: 6,
        totalServices: 422,
        avgServicesPerVisit: 3.2,
        servicesPerVisit: 3.2,
        noServices: "6% (8)",
        assignedOUKRAvg: 94,
        servicesCompletedPercent: 79,
            overKR: 1,
        avgBill: "2 900 ₽",
        revenue: "382 800 ₽",
        potentialRevenue: "401 000 ₽",
        lostOUKRRevenue: "18 200 ₽",
        lostOUKRPercent: 5,
    },
    {
        id: "4",
        fullName: "Смирнов Д.О.",
        profession: "Терапевт",
        appointments: 82,
        primary: 29,
        repeatAppointments: 53,
        requiredKR: 24,
        krServicesDone: 22,
        deviationPercent: 8,
        totalServices: 254,
        avgServicesPerVisit: 3.1,
        servicesPerVisit: 3.1,
        noServices: "7% (6)",
        assignedOUKRAvg: 92,
        servicesCompletedPercent: 78,
            overKR: 1,
        avgBill: "3 100 ₽",
        revenue: "254 200 ₽",
        potentialRevenue: "269 000 ₽",
        lostOUKRRevenue: "14 800 ₽",
        lostOUKRPercent: 6,
    },
    {
        id: "5",
        fullName: "Кузнецов Р.С.",
        profession: "Терапевт",
        appointments: 108,
        primary: 40,
        repeatAppointments: 68,
        requiredKR: 32,
        krServicesDone: 30,
        deviationPercent: 6,
        totalServices: 356,
        avgServicesPerVisit: 3.3,
        servicesPerVisit: 3.3,
        noServices: "6% (7)",
        assignedOUKRAvg: 94,
        servicesCompletedPercent: 80,
            overKR: 2,
        avgBill: "3 300 ₽",
        revenue: "356 400 ₽",
        potentialRevenue: "374 000 ₽",
        lostOUKRRevenue: "17 600 ₽",
        lostOUKRPercent: 5,
    },
    {
        id: "6",
        fullName: "Попов Н.И.",
        profession: "Терапевт",
        appointments: 104,
        primary: 36,
        repeatAppointments: 68,
        requiredKR: 30,
        krServicesDone: 27,
        deviationPercent: 10,
        totalServices: 322,
        avgServicesPerVisit: 3.1,
        servicesPerVisit: 3.1,
        noServices: "9% (9)",
        assignedOUKRAvg: 90,
        servicesCompletedPercent: 77,
            overKR: 1,
        avgBill: "2 950 ₽",
        revenue: "306 800 ₽",
        potentialRevenue: "327 000 ₽",
        lostOUKRRevenue: "20 200 ₽",
        lostOUKRPercent: 7,
    },
    {
        id: "7",
        fullName: "Васильев Е.Д.",
        profession: "Терапевт",
        appointments: 88,
        primary: 30,
        repeatAppointments: 58,
        requiredKR: 26,
        krServicesDone: 25,
        deviationPercent: 4,
        totalServices: 286,
        avgServicesPerVisit: 3.3,
        servicesPerVisit: 3.3,
        noServices: "5% (4)",
        assignedOUKRAvg: 96,
        servicesCompletedPercent: 83,
            overKR: 1,
        avgBill: "3 150 ₽",
        revenue: "277 200 ₽",
        potentialRevenue: "289 000 ₽",
        lostOUKRRevenue: "11 800 ₽",
        lostOUKRPercent: 4,
    },
    {
        id: "8",
        fullName: "Новиков П.А.",
        profession: "Терапевт",
        appointments: 86,
        primary: 31,
        repeatAppointments: 55,
        requiredKR: 23,
        krServicesDone: 22,
        deviationPercent: 5,
        totalServices: 258,
        avgServicesPerVisit: 3,
        servicesPerVisit: 3,
        noServices: "6% (5)",
        assignedOUKRAvg: 95,
        servicesCompletedPercent: 80,
            overKR: 1,
        avgBill: "2 700 ₽",
        revenue: "232 200 ₽",
        potentialRevenue: "242 000 ₽",
        lostOUKRRevenue: "9 800 ₽",
        lostOUKRPercent: 4,
    },
    {
        id: "9",
        fullName: "Фёдоров С.В.",
        profession: "Терапевт",
        appointments: 98,
        primary: 35,
        repeatAppointments: 63,
        requiredKR: 29,
        krServicesDone: 27,
        deviationPercent: 7,
        totalServices: 305,
        avgServicesPerVisit: 3.1,
        servicesPerVisit: 3.1,
        noServices: "7% (7)",
        assignedOUKRAvg: 93,
        servicesCompletedPercent: 79,
            overKR: 1,
        avgBill: "3 000 ₽",
        revenue: "294 000 ₽",
        potentialRevenue: "309 000 ₽",
        lostOUKRRevenue: "15 000 ₽",
        lostOUKRPercent: 5,
    },
    {
        id: "10",
        fullName: "Морозов Л.Г.",
        profession: "Терапевт",
        appointments: 92,
        primary: 33,
        repeatAppointments: 59,
        requiredKR: 27,
        krServicesDone: 25,
        deviationPercent: 7,
        totalServices: 290,
        avgServicesPerVisit: 3.2,
        servicesPerVisit: 3.2,
        noServices: "7% (6)",
        assignedOUKRAvg: 93,
        servicesCompletedPercent: 81,
        overKR: 1,
        avgBill: "3 050 ₽",
        revenue: "280 600 ₽",
        potentialRevenue: "296 000 ₽",
        lostOUKRRevenue: "15 400 ₽",
        lostOUKRPercent: 5,
    },
    {
        id: "11",
        fullName: "Волков А.Н.",
        profession: "Кардиолог",
        appointments: 118,
        primary: 46,
        repeatAppointments: 72,
        requiredKR: 31,
        krServicesDone: 28,
        deviationPercent: 9,
        totalServices: 356,
        avgServicesPerVisit: 3,
        servicesPerVisit: 3,
        noServices: "8% (9)",
        assignedOUKRAvg: 90,
        servicesCompletedPercent: 81,
        overKR: 2,
        avgBill: "2 750 ₽",
        revenue: "324 500 ₽",
        potentialRevenue: "346 000 ₽",
        lostOUKRRevenue: "21 500 ₽",
        lostOUKRPercent: 7,
    },
    {
        id: "12",
        fullName: "Алексеев Д.П.",
        profession: "Кардиолог",
        appointments: 96,
        primary: 34,
        repeatAppointments: 62,
        requiredKR: 29,
        krServicesDone: 28,
        deviationPercent: 4,
        totalServices: 316,
        avgServicesPerVisit: 3.3,
        servicesPerVisit: 3.3,
        noServices: "5% (5)",
        assignedOUKRAvg: 97,
        servicesCompletedPercent: 82,
        overKR: 1,
        avgBill: "3 250 ₽",
        revenue: "312 000 ₽",
        potentialRevenue: "324 000 ₽",
        lostOUKRRevenue: "12 000 ₽",
        lostOUKRPercent: 4,
    },
    {
        id: "13",
        fullName: "Лебедев И.С.",
        profession: "Кардиолог",
        appointments: 132,
        primary: 52,
        repeatAppointments: 80,
        requiredKR: 35,
        krServicesDone: 33,
        deviationPercent: 6,
        totalServices: 422,
        avgServicesPerVisit: 3.2,
        servicesPerVisit: 3.2,
        noServices: "6% (8)",
        assignedOUKRAvg: 94,
        servicesCompletedPercent: 79,
        overKR: 1,
        avgBill: "2 900 ₽",
        revenue: "382 800 ₽",
        potentialRevenue: "401 000 ₽",
        lostOUKRRevenue: "18 200 ₽",
        lostOUKRPercent: 5,
    },
    {
        id: "14",
        fullName: "Семёнов К.М.",
        profession: "Кардиолог",
        appointments: 82,
        primary: 29,
        repeatAppointments: 53,
        requiredKR: 24,
        krServicesDone: 22,
        deviationPercent: 8,
        totalServices: 254,
        avgServicesPerVisit: 3.1,
        servicesPerVisit: 3.1,
        noServices: "7% (6)",
        assignedOUKRAvg: 92,
        servicesCompletedPercent: 78,
        overKR: 1,
        avgBill: "3 100 ₽",
        revenue: "254 200 ₽",
        potentialRevenue: "269 000 ₽",
        lostOUKRRevenue: "14 800 ₽",
        lostOUKRPercent: 6,
    },
    {
        id: "15",
        fullName: "Егоров В.Т.",
        profession: "Кардиолог",
        appointments: 108,
        primary: 40,
        repeatAppointments: 68,
        requiredKR: 32,
        krServicesDone: 30,
        deviationPercent: 6,
        totalServices: 356,
        avgServicesPerVisit: 3.3,
        servicesPerVisit: 3.3,
        noServices: "6% (7)",
        assignedOUKRAvg: 94,
        servicesCompletedPercent: 80,
        overKR: 2,
        avgBill: "3 300 ₽",
        revenue: "356 400 ₽",
        potentialRevenue: "374 000 ₽",
        lostOUKRRevenue: "17 600 ₽",
        lostOUKRPercent: 5,
    },
    {
        id: "16",
        fullName: "Павлов Р.А.",
        profession: "Кардиолог",
        appointments: 104,
        primary: 36,
        repeatAppointments: 68,
        requiredKR: 30,
        krServicesDone: 27,
        deviationPercent: 10,
        totalServices: 322,
        avgServicesPerVisit: 3.1,
        servicesPerVisit: 3.1,
        noServices: "9% (9)",
        assignedOUKRAvg: 90,
        servicesCompletedPercent: 77,
        overKR: 1,
        avgBill: "2 950 ₽",
        revenue: "306 800 ₽",
        potentialRevenue: "327 000 ₽",
        lostOUKRRevenue: "20 200 ₽",
        lostOUKRPercent: 7,
    },
    {
        id: "17",
        fullName: "Козлов О.В.",
        profession: "Кардиолог",
        appointments: 88,
        primary: 30,
        repeatAppointments: 58,
        requiredKR: 26,
        krServicesDone: 25,
        deviationPercent: 4,
        totalServices: 286,
        avgServicesPerVisit: 3.3,
        servicesPerVisit: 3.3,
        noServices: "5% (4)",
        assignedOUKRAvg: 96,
        servicesCompletedPercent: 83,
        overKR: 1,
        avgBill: "3 150 ₽",
        revenue: "277 200 ₽",
        potentialRevenue: "289 000 ₽",
        lostOUKRRevenue: "11 800 ₽",
        lostOUKRPercent: 4,
    },
    {
        id: "18",
        fullName: "Степанов М.Е.",
        profession: "Кардиолог",
        appointments: 86,
        primary: 31,
        repeatAppointments: 55,
        requiredKR: 23,
        krServicesDone: 22,
        deviationPercent: 5,
        totalServices: 258,
        avgServicesPerVisit: 3,
        servicesPerVisit: 3,
        noServices: "6% (5)",
        assignedOUKRAvg: 95,
        servicesCompletedPercent: 80,
        overKR: 1,
        avgBill: "2 700 ₽",
        revenue: "232 200 ₽",
        potentialRevenue: "242 000 ₽",
        lostOUKRRevenue: "9 800 ₽",
        lostOUKRPercent: 4,
    },
    {
        id: "19",
        fullName: "Никитин С.П.",
        profession: "Кардиолог",
        appointments: 98,
        primary: 35,
        repeatAppointments: 63,
        requiredKR: 29,
        krServicesDone: 27,
        deviationPercent: 7,
        totalServices: 305,
        avgServicesPerVisit: 3.1,
        servicesPerVisit: 3.1,
        noServices: "7% (7)",
        assignedOUKRAvg: 93,
        servicesCompletedPercent: 79,
        overKR: 1,
        avgBill: "3 000 ₽",
        revenue: "294 000 ₽",
        potentialRevenue: "309 000 ₽",
        lostOUKRRevenue: "15 000 ₽",
        lostOUKRPercent: 5,
    },
    {
        id: "20",
        fullName: "Захаров Д.И.",
        profession: "Кардиолог",
        appointments: 92,
        primary: 33,
        repeatAppointments: 59,
        requiredKR: 27,
        krServicesDone: 25,
        deviationPercent: 7,
        totalServices: 290,
        avgServicesPerVisit: 3.2,
        servicesPerVisit: 3.2,
        noServices: "7% (6)",
        assignedOUKRAvg: 93,
        servicesCompletedPercent: 81,
        overKR: 1,
        avgBill: "3 050 ₽",
        revenue: "280 600 ₽",
        potentialRevenue: "296 000 ₽",
        lostOUKRRevenue: "15 400 ₽",
        lostOUKRPercent: 5,
    },
    {
        id: "21",
        fullName: "Макаров А.С.",
        profession: "Эндокринолог",
        appointments: 118,
        primary: 46,
        repeatAppointments: 72,
        requiredKR: 31,
        krServicesDone: 28,
        deviationPercent: 9,
        totalServices: 356,
        avgServicesPerVisit: 3,
        servicesPerVisit: 3,
        noServices: "8% (9)",
        assignedOUKRAvg: 90,
        servicesCompletedPercent: 81,
        overKR: 2,
        avgBill: "2 750 ₽",
        revenue: "324 500 ₽",
        potentialRevenue: "346 000 ₽",
        lostOUKRRevenue: "21 500 ₽",
        lostOUKRPercent: 7,
    },
    {
        id: "22",
        fullName: "Андреев И.Н.",
        profession: "Эндокринолог",
        appointments: 96,
        primary: 34,
        repeatAppointments: 62,
        requiredKR: 29,
        krServicesDone: 28,
        deviationPercent: 4,
        totalServices: 316,
        avgServicesPerVisit: 3.3,
        servicesPerVisit: 3.3,
        noServices: "5% (5)",
        assignedOUKRAvg: 97,
        servicesCompletedPercent: 82,
        overKR: 1,
        avgBill: "3 250 ₽",
        revenue: "312 000 ₽",
        potentialRevenue: "324 000 ₽",
        lostOUKRRevenue: "12 000 ₽",
        lostOUKRPercent: 4,
    },
    {
        id: "23",
        fullName: "Тарасов В.О.",
        profession: "Эндокринолог",
        appointments: 132,
        primary: 52,
        repeatAppointments: 80,
        requiredKR: 35,
        krServicesDone: 33,
        deviationPercent: 6,
        totalServices: 422,
        avgServicesPerVisit: 3.2,
        servicesPerVisit: 3.2,
        noServices: "6% (8)",
        assignedOUKRAvg: 94,
        servicesCompletedPercent: 79,
        overKR: 1,
        avgBill: "2 900 ₽",
        revenue: "382 800 ₽",
        potentialRevenue: "401 000 ₽",
        lostOUKRRevenue: "18 200 ₽",
        lostOUKRPercent: 5,
    },
    {
        id: "24",
        fullName: "Беляев К.Д.",
        profession: "Эндокринолог",
        appointments: 82,
        primary: 29,
        repeatAppointments: 53,
        requiredKR: 24,
        krServicesDone: 22,
        deviationPercent: 8,
        totalServices: 254,
        avgServicesPerVisit: 3.1,
        servicesPerVisit: 3.1,
        noServices: "7% (6)",
        assignedOUKRAvg: 92,
        servicesCompletedPercent: 78,
        overKR: 1,
        avgBill: "3 100 ₽",
        revenue: "254 200 ₽",
        potentialRevenue: "269 000 ₽",
        lostOUKRRevenue: "14 800 ₽",
        lostOUKRPercent: 6,
    },
    {
        id: "25",
        fullName: "Комаров П.В.",
        profession: "Эндокринолог",
        appointments: 108,
        primary: 40,
        repeatAppointments: 68,
        requiredKR: 32,
        krServicesDone: 30,
        deviationPercent: 6,
        totalServices: 356,
        avgServicesPerVisit: 3.3,
        servicesPerVisit: 3.3,
        noServices: "6% (7)",
        assignedOUKRAvg: 94,
        servicesCompletedPercent: 80,
        overKR: 2,
        avgBill: "3 300 ₽",
        revenue: "356 400 ₽",
        potentialRevenue: "374 000 ₽",
        lostOUKRRevenue: "17 600 ₽",
        lostOUKRPercent: 5,
    },
    {
        id: "26",
        fullName: "Орлов Р.М.",
        profession: "Эндокринолог",
        appointments: 104,
        primary: 36,
        repeatAppointments: 68,
        requiredKR: 30,
        krServicesDone: 27,
        deviationPercent: 10,
        totalServices: 322,
        avgServicesPerVisit: 3.1,
        servicesPerVisit: 3.1,
        noServices: "9% (9)",
        assignedOUKRAvg: 90,
        servicesCompletedPercent: 77,
        overKR: 1,
        avgBill: "2 950 ₽",
        revenue: "306 800 ₽",
        potentialRevenue: "327 000 ₽",
        lostOUKRRevenue: "20 200 ₽",
        lostOUKRPercent: 7,
    },
    {
        id: "27",
        fullName: "Киселёв С.А.",
        profession: "Эндокринолог",
        appointments: 88,
        primary: 30,
        repeatAppointments: 58,
        requiredKR: 26,
        krServicesDone: 25,
        deviationPercent: 4,
        totalServices: 286,
        avgServicesPerVisit: 3.3,
        servicesPerVisit: 3.3,
        noServices: "5% (4)",
        assignedOUKRAvg: 96,
        servicesCompletedPercent: 83,
        overKR: 1,
        avgBill: "3 150 ₽",
        revenue: "277 200 ₽",
        potentialRevenue: "289 000 ₽",
        lostOUKRRevenue: "11 800 ₽",
        lostOUKRPercent: 4,
    },
    {
        id: "28",
        fullName: "Громов Д.С.",
        profession: "Эндокринолог",
        appointments: 86,
        primary: 31,
        repeatAppointments: 55,
        requiredKR: 23,
        krServicesDone: 22,
        deviationPercent: 5,
        totalServices: 258,
        avgServicesPerVisit: 3,
        servicesPerVisit: 3,
        noServices: "6% (5)",
        assignedOUKRAvg: 95,
        servicesCompletedPercent: 80,
        overKR: 1,
        avgBill: "2 700 ₽",
        revenue: "232 200 ₽",
        potentialRevenue: "242 000 ₽",
        lostOUKRRevenue: "9 800 ₽",
        lostOUKRPercent: 4,
    },
    {
        id: "29",
        fullName: "Денисов И.К.",
        profession: "Эндокринолог",
        appointments: 98,
        primary: 35,
        repeatAppointments: 63,
        requiredKR: 29,
        krServicesDone: 27,
        deviationPercent: 7,
        totalServices: 305,
        avgServicesPerVisit: 3.1,
        servicesPerVisit: 3.1,
        noServices: "7% (7)",
        assignedOUKRAvg: 93,
        servicesCompletedPercent: 79,
        overKR: 1,
        avgBill: "3 000 ₽",
        revenue: "294 000 ₽",
        potentialRevenue: "309 000 ₽",
        lostOUKRRevenue: "15 000 ₽",
        lostOUKRPercent: 5,
    },
    {
        id: "30",
        fullName: "Григорьев А.В.",
        profession: "Эндокринолог",
        appointments: 92,
        primary: 33,
        repeatAppointments: 59,
        requiredKR: 27,
        krServicesDone: 25,
        deviationPercent: 7,
        totalServices: 290,
        avgServicesPerVisit: 3.2,
        servicesPerVisit: 3.2,
        noServices: "7% (6)",
        assignedOUKRAvg: 93,
        servicesCompletedPercent: 81,
        overKR: 1,
        avgBill: "3 050 ₽",
        revenue: "280 600 ₽",
        potentialRevenue: "296 000 ₽",
        lostOUKRRevenue: "15 400 ₽",
        lostOUKRPercent: 5,
    },
    {
        id: "31",
        fullName: "Белов Н.С.",
        profession: "Пульмонолог",
        appointments: 118,
        primary: 46,
        repeatAppointments: 72,
        requiredKR: 31,
        krServicesDone: 28,
        deviationPercent: 9,
        totalServices: 356,
        avgServicesPerVisit: 3,
        servicesPerVisit: 3,
        noServices: "8% (9)",
        assignedOUKRAvg: 90,
        servicesCompletedPercent: 81,
        overKR: 2,
        avgBill: "2 750 ₽",
        revenue: "324 500 ₽",
        potentialRevenue: "346 000 ₽",
        lostOUKRRevenue: "21 500 ₽",
        lostOUKRPercent: 7,
    },
    {
        id: "32",
        fullName: "Савельев Д.А.",
        profession: "Пульмонолог",
        appointments: 96,
        primary: 34,
        repeatAppointments: 62,
        requiredKR: 29,
        krServicesDone: 28,
        deviationPercent: 4,
        totalServices: 316,
        avgServicesPerVisit: 3.3,
        servicesPerVisit: 3.3,
        noServices: "5% (5)",
        assignedOUKRAvg: 97,
        servicesCompletedPercent: 82,
        overKR: 1,
        avgBill: "3 250 ₽",
        revenue: "312 000 ₽",
        potentialRevenue: "324 000 ₽",
        lostOUKRRevenue: "12 000 ₽",
        lostOUKRPercent: 4,
    },
    {
        id: "33",
        fullName: "Мельников И.О.",
        profession: "Пульмонолог",
        appointments: 132,
        primary: 52,
        repeatAppointments: 80,
        requiredKR: 35,
        krServicesDone: 33,
        deviationPercent: 6,
        totalServices: 422,
        avgServicesPerVisit: 3.2,
        servicesPerVisit: 3.2,
        noServices: "6% (8)",
        assignedOUKRAvg: 94,
        servicesCompletedPercent: 79,
        overKR: 1,
        avgBill: "2 900 ₽",
        revenue: "382 800 ₽",
        potentialRevenue: "401 000 ₽",
        lostOUKRRevenue: "18 200 ₽",
        lostOUKRPercent: 5,
    },
    {
        id: "34",
        fullName: "Щербаков К.В.",
        profession: "Пульмонолог",
        appointments: 82,
        primary: 29,
        repeatAppointments: 53,
        requiredKR: 24,
        krServicesDone: 22,
        deviationPercent: 8,
        totalServices: 254,
        avgServicesPerVisit: 3.1,
        servicesPerVisit: 3.1,
        noServices: "7% (6)",
        assignedOUKRAvg: 92,
        servicesCompletedPercent: 78,
        overKR: 1,
        avgBill: "3 100 ₽",
        revenue: "254 200 ₽",
        potentialRevenue: "269 000 ₽",
        lostOUKRRevenue: "14 800 ₽",
        lostOUKRPercent: 6,
    },
    {
        id: "35",
        fullName: "Калинин Р.Д.",
        profession: "Пульмонолог",
        appointments: 108,
        primary: 40,
        repeatAppointments: 68,
        requiredKR: 32,
        krServicesDone: 30,
        deviationPercent: 6,
        totalServices: 356,
        avgServicesPerVisit: 3.3,
        servicesPerVisit: 3.3,
        noServices: "6% (7)",
        assignedOUKRAvg: 94,
        servicesCompletedPercent: 80,
        overKR: 2,
        avgBill: "3 300 ₽",
        revenue: "356 400 ₽",
        potentialRevenue: "374 000 ₽",
        lostOUKRRevenue: "17 600 ₽",
        lostOUKRPercent: 5,
    },
    {
        id: "36",
        fullName: "Зайцев П.С.",
        profession: "Пульмонолог",
        appointments: 104,
        primary: 36,
        repeatAppointments: 68,
        requiredKR: 30,
        krServicesDone: 27,
        deviationPercent: 10,
        totalServices: 322,
        avgServicesPerVisit: 3.1,
        servicesPerVisit: 3.1,
        noServices: "9% (9)",
        assignedOUKRAvg: 90,
        servicesCompletedPercent: 77,
        overKR: 1,
        avgBill: "2 950 ₽",
        revenue: "306 800 ₽",
        potentialRevenue: "327 000 ₽",
        lostOUKRRevenue: "20 200 ₽",
        lostOUKRPercent: 7,
    },
    {
        id: "37",
        fullName: "Титов М.А.",
        profession: "Пульмонолог",
        appointments: 88,
        primary: 30,
        repeatAppointments: 58,
        requiredKR: 26,
        krServicesDone: 25,
        deviationPercent: 4,
        totalServices: 286,
        avgServicesPerVisit: 3.3,
        servicesPerVisit: 3.3,
        noServices: "5% (4)",
        assignedOUKRAvg: 96,
        servicesCompletedPercent: 83,
        overKR: 1,
        avgBill: "3 150 ₽",
        revenue: "277 200 ₽",
        potentialRevenue: "289 000 ₽",
        lostOUKRRevenue: "11 800 ₽",
        lostOUKRPercent: 4,
    },
    {
        id: "38",
        fullName: "Виноградов Е.И.",
        profession: "Пульмонолог",
        appointments: 86,
        primary: 31,
        repeatAppointments: 55,
        requiredKR: 23,
        krServicesDone: 22,
        deviationPercent: 5,
        totalServices: 258,
        avgServicesPerVisit: 3,
        servicesPerVisit: 3,
        noServices: "6% (5)",
        assignedOUKRAvg: 95,
        servicesCompletedPercent: 80,
        overKR: 1,
        avgBill: "2 700 ₽",
        revenue: "232 200 ₽",
        potentialRevenue: "242 000 ₽",
        lostOUKRRevenue: "9 800 ₽",
        lostOUKRPercent: 4,
    },
    {
        id: "39",
        fullName: "Королёв С.Д.",
        profession: "Пульмонолог",
        appointments: 98,
        primary: 35,
        repeatAppointments: 63,
        requiredKR: 29,
        krServicesDone: 27,
        deviationPercent: 7,
        totalServices: 305,
        avgServicesPerVisit: 3.1,
        servicesPerVisit: 3.1,
        noServices: "7% (7)",
        assignedOUKRAvg: 93,
        servicesCompletedPercent: 79,
        overKR: 1,
        avgBill: "3 000 ₽",
        revenue: "294 000 ₽",
        potentialRevenue: "309 000 ₽",
        lostOUKRRevenue: "15 000 ₽",
        lostOUKRPercent: 5,
    },
    {
        id: "40",
        fullName: "Ильин О.П.",
        profession: "Пульмонолог",
        appointments: 92,
        primary: 33,
        repeatAppointments: 59,
        requiredKR: 27,
        krServicesDone: 25,
        deviationPercent: 7,
        totalServices: 290,
        avgServicesPerVisit: 3.2,
        servicesPerVisit: 3.2,
        noServices: "7% (6)",
        assignedOUKRAvg: 93,
        servicesCompletedPercent: 81,
        overKR: 1,
        avgBill: "3 050 ₽",
        revenue: "280 600 ₽",
        potentialRevenue: "296 000 ₽",
        lostOUKRRevenue: "15 400 ₽",
        lostOUKRPercent: 5,
    },
];

export async function GET() {
    return NextResponse.json(doctors);
}
