import { NextResponse } from "next/server";

export async function GET() {
    const specialties = [
        {
            id: "1",
            name: "Терапия",
            appointments: 420,
            noServices: 32,
            requiredKR: 180,
            assignedOUKRPercent: 88,
            servicesCompletedPercent: 82,
            deviationOUKRPercent: 10,
            avgOUKRAssign: 2.8,
            avgNosologyAssign: 3.2,
            totalServices: 520,
            overKR: 45,
            revenue: "2 450 000 ₽",
            avgBill: "2 800 ₽",
            potentialRevenue: "2 800 000 ₽",
            lostOUKRRevenue: "350 000 ₽",
            lostOUKRPercent: 12,
        },
        {
            id: "2",
            name: "Кардиология",
            appointments: 310,
            noServices: 18,
            requiredKR: 140,
            assignedOUKRPercent: 91,
            servicesCompletedPercent: 86,
            deviationOUKRPercent: 7,
            avgOUKRAssign: 3.1,
            avgNosologyAssign: 3.4,
            totalServices: 430,
            overKR: 30,
            revenue: "2 100 000 ₽",
            avgBill: "3 200 ₽",
            potentialRevenue: "2 400 000 ₽",
            lostOUKRRevenue: "300 000 ₽",
            lostOUKRPercent: 9,
        },
        {
            id: "3",
            name: "Эндокринология",
            appointments: 260,
            noServices: 22,
            requiredKR: 120,
            assignedOUKRPercent: 85,
            servicesCompletedPercent: 78,
            deviationOUKRPercent: 14,
            avgOUKRAssign: 2.6,
            avgNosologyAssign: 3.0,
            totalServices: 390,
            overKR: 38,
            revenue: "1 850 000 ₽",
            avgBill: "3 000 ₽",
            potentialRevenue: "2 200 000 ₽",
            lostOUKRRevenue: "350 000 ₽",
            lostOUKRPercent: 16,
        },
    ];

    return NextResponse.json(specialties);
}
