import { NextResponse } from "next/server";

export async function GET() {
    const specialties = [
        {
            id: "1",
            name: "Терапия",
            appointments: 336,
                noServices: 22,
            requiredKR: 89,
            assignedOUKRPercent: 93,
            servicesCompletedPercent: 80,
            deviationOUKRPercent: 6,
            avgOUKRAssign: 3,
            avgNosologyAssign: 3.2,
            totalServices: 1036,
                overKR: 4,
            revenue: "939 500 ₽",
            avgBill: "2 800 ₽",
            potentialRevenue: "989 000 ₽",
                lostOUKRRevenue: "49 500 ₽",
            lostOUKRPercent: 5,
        },
        {
            id: "2",
            name: "Кардиология",
            appointments: 384,
                noServices: 22,
            requiredKR: 114,
            assignedOUKRPercent: 95,
            servicesCompletedPercent: 82,
            deviationOUKRPercent: 5,
            avgOUKRAssign: 3.2,
            avgNosologyAssign: 3.4,
            totalServices: 1248,
                overKR: 5,
            revenue: "1 226 200 ₽",
            avgBill: "3 190 ₽",
            potentialRevenue: "1 283 000 ₽",
            lostOUKRRevenue: "56 800 ₽",
            lostOUKRPercent: 5,
        },
        {
            id: "3",
            name: "Эндокринология",
            appointments: 284,
                noServices: 22,
            requiredKR: 83,
                assignedOUKRPercent: 92,
            servicesCompletedPercent: 78,
            deviationOUKRPercent: 8,
            avgOUKRAssign: 3.1,
            avgNosologyAssign: 3.2,
            totalServices: 881,
            overKR: 3,
            revenue: "855 000 ₽",
            avgBill: "3 010 ₽",
            potentialRevenue: "905 000 ₽",
            lostOUKRRevenue: "50 000 ₽",
            lostOUKRPercent: 6,
        },
];

    return NextResponse.json(specialties);
}
