import { NextResponse } from "next/server";

type Appointment = {
    id: string;
    doctorId: string;
    date: string;
    number: string;
    requiredServices: number;
    assignedRequired: number;
    assignedTotal?: number;
    assignmentPercent: number;
    completionPercent: number;
    deviationPercent: number;
    revenue: string;
    lostRevenue: string;
    mkb: string;
};

const appointments: Appointment[] = [
    { id: "a1",
        doctorId: "3",
        date: "15.02.2026",
        number: "№1", mkb: "I21.0",
        requiredServices: 6,
        assignedRequired: 6,
        assignmentPercent: 100,
        assignedTotal: 8,
        completionPercent: 100,
        deviationPercent: 0,
        revenue: "20 712 ₽",
        lostRevenue: "0 ₽" },

    { id: "a2",
        doctorId: "3",
        date: "15.02.2026",
        number: "№2", mkb: "I21.1",
        requiredServices: 5,
        assignedRequired: 1,
        assignmentPercent: 20,
        assignedTotal: 2,
        completionPercent: 0,
        deviationPercent: 100,
        revenue: "0 ₽",
        lostRevenue: "17 260 ₽" },

    { id: "a3",
        doctorId: "3",
        date: "15.02.2026",
        number: "№3", mkb: "I21.2",
        requiredServices: 4,
        assignedRequired: 3,
        assignmentPercent: 67,
        assignedTotal: 6,
        completionPercent: 50,
        deviationPercent: 75,
        revenue: "6 904 ₽",
        lostRevenue: "13 808 ₽" },

    { id: "a4",
        doctorId: "3",
        date: "15.02.2026",
        number: "№4", mkb: "I21.3",
        requiredServices: 7,
        assignedRequired: 6,
        assignmentPercent: 87,
        assignedTotal: 10,
        completionPercent: 70,
        deviationPercent: 29,
        revenue: "17 260 ₽",
        lostRevenue: "6 904 ₽" },

    { id: "a5",
        doctorId: "3",
        date: "15.02.2026",
        number: "№5", mkb: "I21.9",
        requiredServices: 6,
        assignedRequired: 2,
        assignmentPercent: 33,
        completionPercent: 100,
        deviationPercent: 67,
        revenue: "6 904 ₽",
        lostRevenue: "13 808 ₽" },

    { id: "a6",
        doctorId: "3",
        date: "16.02.2026",
        number: "№6", mkb: "I22.0",
        requiredServices: 5,
        assignedRequired: 5,
        assignmentPercent: 100,
        completionPercent: 60,
        deviationPercent: 40,
        revenue: "10 356 ₽",
        lostRevenue: "6 904 ₽" },

    { id: "a7",
        doctorId: "3",
        date: "16.02.2026",
        number: "№7", mkb: "I22.1",
        requiredServices: 6,
        assignedRequired: 3,
        assignmentPercent: 50,
        completionPercent: 33,
        deviationPercent: 83,
        revenue: "3 452 ₽",
        lostRevenue: "17 260 ₽" },

    { id: "a8",
        doctorId: "3",
        date: "16.02.2026",
        number: "№8", mkb: "I22.8",
        requiredServices: 7,
        assignedRequired: 2,
        assignmentPercent: 29,
        completionPercent: 0,
        deviationPercent: 100,
        revenue: "0 ₽",
        lostRevenue: "24 164 ₽" },

    { id: "a9",
        doctorId: "3",
        date: "16.02.2026",
        number: "№9", mkb: "I22.9",
        requiredServices: 6,
        assignedRequired: 6,
        assignmentPercent: 100,
        completionPercent: 67,
        deviationPercent: 33,
        revenue: "13 808 ₽",
        lostRevenue: "6 904 ₽" },

    { id: "a10",
        doctorId: "3",
        date: "16.02.2026",
        number: "№10", mkb: "I24.0",
        requiredServices: 6,
        assignedRequired: 1,
        assignmentPercent: 17,
        completionPercent: 100,
        deviationPercent: 83,
        revenue: "3 452 ₽",
        lostRevenue: "17 260 ₽" },

    { id: "a11",
        doctorId: "3",
        date: "17.02.2026",
        number: "№11", mkb: "I24.8",
        requiredServices: 7,
        assignedRequired: 5,
        assignmentPercent: 71,
        completionPercent: 100,
        deviationPercent: 29,
        revenue: "17 260 ₽",
        lostRevenue: "6 904 ₽" },

    { id: "a12",
        doctorId: "3",
        date: "17.02.2026",
        number: "№12", mkb: "I24.9",
        requiredServices: 5,
        assignedRequired: 1,
        assignmentPercent: 0,
        completionPercent: 0,
        deviationPercent: 100,
        revenue: "0 ₽",
        lostRevenue: "17 260 ₽" },

    { id: "a13",
        doctorId: "3",
        date: "17.02.2026",
        number: "№13", mkb: "I21.0",
        requiredServices: 6,
        assignedRequired: 4,
        assignmentPercent: 67,
        completionPercent: 100,
        deviationPercent: 33,
        revenue: "13 808 ₽",
        lostRevenue: "6 904 ₽" },

    { id: "a14",
        doctorId: "3",
        date: "17.02.2026",
        number: "№14", mkb: "I21.2",
        requiredServices: 6,
        assignedRequired: 3,
        assignmentPercent: 50,
        completionPercent: 100,
        deviationPercent: 50,
        revenue: "10 356 ₽",
        lostRevenue: "10 356 ₽" },

    { id: "a15",
        doctorId: "3",
        date: "17.02.2026",
        number: "№15", mkb: "I21.3",
        requiredServices: 7,
        assignedRequired: 1,
        assignmentPercent: 14,
        completionPercent: 0,
        deviationPercent: 100,
        revenue: "0 ₽",
        lostRevenue: "24 164 ₽" },

    { id: "a16",
        doctorId: "3",
        date: "18.02.2026",
        number: "№16", mkb: "I22.0",
        requiredServices: 5,
        assignedRequired: 4,
        assignmentPercent: 80,
        completionPercent: 50,
        deviationPercent: 60,
        revenue: "6 904 ₽",
        lostRevenue: "10 356 ₽" },

    { id: "a17",
        doctorId: "3",
        date: "18.02.2026",
        number: "№17", mkb: "I22.8",
        requiredServices: 7,
        assignedRequired: 6,
        assignmentPercent: 86,
        completionPercent: 100,
        deviationPercent: 14,
        revenue: "20 712 ₽",
        lostRevenue: "3 452 ₽" },

    { id: "a18",
        doctorId: "3",
        date: "18.02.2026",
        number: "№18", mkb: "I22.9",
        requiredServices: 6,
        assignedRequired: 2,
        assignmentPercent: 33,
        completionPercent: 50,
        deviationPercent: 83,
        revenue: "3 452 ₽",
        lostRevenue: "17 260 ₽" },

    { id: "a19",
        doctorId: "3",
        date: "18.02.2026",
        number: "№19", mkb: "I24.0",
        requiredServices: 6,
        assignedRequired: 5,
        assignmentPercent: 83,
        completionPercent: 60,
        deviationPercent: 50,
        revenue: "10 356 ₽",
        lostRevenue: "10 356 ₽" },

    { id: "a20",
        doctorId: "3",
        date: "18.02.2026",
        number: "№20", mkb: "I24.9",
        requiredServices: 5,
        assignedRequired: 3,
        assignmentPercent: 60,
        completionPercent: 100,
        deviationPercent: 40,
        revenue: "10 356 ₽",
        lostRevenue: "6 904 ₽" },
    { id: "a21",
        doctorId: "3",
        date: "19.02.2026",
        number: "№21", mkb: "I21.1",
        requiredServices: 6,
        assignedRequired: 6,
        assignmentPercent: 100,
        completionPercent: 100,
        deviationPercent: 0,
        revenue: "20 712 ₽",
        lostRevenue: "0 ₽" },

    { id: "a22",
        doctorId: "3",
        date: "19.02.2026",
        number: "№22", mkb: "I21.2",
        requiredServices: 5,
        assignedRequired: 1,
        assignmentPercent: 20,
        completionPercent: 100,
        deviationPercent: 80,
        revenue: "3 452 ₽",
        lostRevenue: "13 808 ₽" },

    { id: "a23",
        doctorId: "3",
        date: "19.02.2026",
        number: "№23", mkb: "I21.3",
        requiredServices: 7,
        assignedRequired: 3,
        assignmentPercent: 43,
        completionPercent: 0,
        deviationPercent: 100,
        revenue: "0 ₽",
        lostRevenue: "24 164 ₽" },

    { id: "a24",
        doctorId: "3",
        date: "19.02.2026",
        number: "№24", mkb: "I21.9",
        requiredServices: 6,
        assignedRequired: 5,
        assignmentPercent: 83,
        completionPercent: 100,
        deviationPercent: 17,
        revenue: "17 260 ₽",
        lostRevenue: "3 452 ₽" },

    { id: "a25",
        doctorId: "3",
        date: "19.02.2026",
        number: "№25", mkb: "I22.0",
        requiredServices: 5,
        assignedRequired: 4,
        assignmentPercent: 80,
        completionPercent: 100,
        deviationPercent: 20,
        revenue: "13 808 ₽",
        lostRevenue: "3 452 ₽" },

    { id: "a26",
        doctorId: "3",
        date: "20.02.2026",
        number: "№26", mkb: "I22.1",
        requiredServices: 6,
        assignedRequired: 2,
        assignmentPercent: 33,
        completionPercent: 50,
        deviationPercent: 83,
        revenue: "3 452 ₽",
        lostRevenue: "17 260 ₽" },

    { id: "a27",
        doctorId: "3",
        date: "20.02.2026",
        number: "№27", mkb: "I22.8",
        requiredServices: 7,
        assignedRequired: 7,
        assignmentPercent: 100,
        completionPercent: 29,
        deviationPercent: 71,
        revenue: "6 904 ₽",
        lostRevenue: "17 260 ₽" },

    { id: "a28",
        doctorId: "3",
        date: "20.02.2026",
        number: "№28", mkb: "I22.9",
        requiredServices: 6,
        assignedRequired: 3,
        assignmentPercent: 50,
        completionPercent: 100,
        deviationPercent: 50,
        revenue: "10 356 ₽",
        lostRevenue: "10 356 ₽" },

    { id: "a29",
        doctorId: "3",
        date: "20.02.2026",
        number: "№29", mkb: "I24.0",
        requiredServices: 6,
        assignedRequired: 1,
        assignmentPercent: 0,
        completionPercent: 0,
        deviationPercent: 100,
        revenue: "0 ₽",
        lostRevenue: "20 712 ₽" },


    { id: "a30",
        doctorId: "3",
        date: "20.02.2026",
        number: "№30", mkb: "I24.8",
        requiredServices: 7,
        assignedRequired: 6,
        assignmentPercent: 86,
        completionPercent: 67,
        deviationPercent: 43,
        revenue: "13 808 ₽",
        lostRevenue: "10 356 ₽" },

    { id: "a31",
        doctorId: "3",
        date: "21.02.2026",
        number: "№31", mkb: "I24.9",
        requiredServices: 5,
        assignedRequired: 2,
        assignmentPercent: 40,
        completionPercent: 100,
        deviationPercent: 60,
        revenue: "6 904 ₽",
        lostRevenue: "10 356 ₽" },

    { id: "a32",
        doctorId: "3",
        date: "21.02.2026",
        number: "№32", mkb: "I21.0",
        requiredServices: 6,
        assignedRequired: 6,
        assignmentPercent: 100,
        completionPercent: 83,
        deviationPercent: 17,
        revenue: "17 260 ₽",
        lostRevenue: "3 452 ₽" },

    { id: "a33",
        doctorId: "3",
        date: "21.02.2026",
        number: "№33", mkb: "I21.1",
        requiredServices: 5,
        assignedRequired: 3,
        assignmentPercent: 60,
        completionPercent: 0,
        deviationPercent: 100,
        revenue: "0 ₽",
        lostRevenue: "17 260 ₽" },

    { id: "a34",
        doctorId: "3",
        date: "21.02.2026",
        number: "№34", mkb: "I21.2",
        requiredServices: 6,
        assignedRequired: 4,
        assignmentPercent: 67,
        completionPercent: 100,
        deviationPercent: 33,
        revenue: "13 808 ₽",
        lostRevenue: "6 904 ₽" },

    { id: "a35",
        doctorId: "3",
        date: "21.02.2026",
        number: "№35", mkb: "I21.3",
        requiredServices: 7,
        assignedRequired: 1,
        assignmentPercent: 14,
        completionPercent: 100,
        deviationPercent: 86,
        revenue: "3 452 ₽",
        lostRevenue: "20 712 ₽" },

    { id: "a36",
        doctorId: "3",
        date: "22.02.2026",
        number: "№36", mkb: "I21.9",
        requiredServices: 6,
        assignedRequired: 5,
        assignmentPercent: 83,
        completionPercent: 40,
        deviationPercent: 67,
        revenue: "6 904 ₽",
        lostRevenue: "13 808 ₽" },

    { id: "a37",
        doctorId: "3",
        date: "22.02.2026",
        number: "№37", mkb: "I22.0",
        requiredServices: 5,
        assignedRequired: 5,
        assignmentPercent: 100,
        completionPercent: 100,
        deviationPercent: 0,
        revenue: "17 260 ₽",
        lostRevenue: "0 ₽" },

    { id: "a38",
        doctorId: "3",
        date: "22.02.2026",
        number: "№38", mkb: "I22.1",
        requiredServices: 6,
        assignedRequired: 3,
        assignmentPercent: 50,
        completionPercent: 67,
        deviationPercent: 67,
        revenue: "6 904 ₽",
        lostRevenue: "13 808 ₽" },

    { id: "a39",
        doctorId: "3",
        date: "22.02.2026",
        number: "№39", mkb: "I22.8",
        requiredServices: 7,
        assignedRequired: 4,
        assignmentPercent: 57,
        completionPercent: 100,
        deviationPercent: 43,
        revenue: "13 808 ₽",
        lostRevenue: "10 356 ₽" },

    { id: "a40",
        doctorId: "3",
        date: "22.02.2026",
        number: "№40", mkb: "I22.9",
        requiredServices: 6,
        assignedRequired: 2,
        assignmentPercent: 33,
        completionPercent: 0,
        deviationPercent: 100,
        revenue: "0 ₽",
        lostRevenue: "20 712 ₽" },

    { id: "a41",
        doctorId: "3",
        date: "23.02.2026",
        number: "№41", mkb: "I24.0",
        requiredServices: 6,
        assignedRequired: 6,
        assignmentPercent: 100,
        completionPercent: 50,
        deviationPercent: 50,
        revenue: "10 356 ₽",
        lostRevenue: "10 356 ₽" },

    { id: "a42",
        doctorId: "3",
        date: "23.02.2026",
        number: "№42", mkb: "I24.8",
        requiredServices: 7,
        assignedRequired: 2,
        assignmentPercent: 29,
        completionPercent: 100,
        deviationPercent: 71,
        revenue: "6 904 ₽",
        lostRevenue: "17 260 ₽" },

    { id: "a43",
        doctorId: "3",
        date: "23.02.2026",
        number: "№43", mkb: "I24.9",
        requiredServices: 5,
        assignedRequired: 4,
        assignmentPercent: 80,
        completionPercent: 100,
        deviationPercent: 20,
        revenue: "13 808 ₽",
        lostRevenue: "3 452 ₽" },

    { id: "a44",
        doctorId: "3",
        date: "23.02.2026",
        number: "№44", mkb: "I21.0",
        requiredServices: 6,
        assignedRequired: 1,
        assignmentPercent: 17,
        completionPercent: 0,
        deviationPercent: 100,
        revenue: "0 ₽",
        lostRevenue: "20 712 ₽" },

    { id: "a45",
        doctorId: "3",
        date: "23.02.2026",
        number: "№45", mkb: "I21.2",
        requiredServices: 6,
        assignedRequired: 5,
        assignmentPercent: 83,
        completionPercent: 100,
        deviationPercent: 17,
        revenue: "17 260 ₽",
        lostRevenue: "3 452 ₽" },

    { id: "a46",
        doctorId: "3",
        date: "24.02.2026",
        number: "№46", mkb: "I21.3",
        requiredServices: 7,
        assignedRequired: 3,
        assignmentPercent: 43,
        completionPercent: 33,
        deviationPercent: 86,
        revenue: "3 452 ₽",
        lostRevenue: "20 712 ₽" },

    { id: "a47",
        doctorId: "3",
        date: "24.02.2026",
        number: "№47", mkb: "I21.9",
        requiredServices: 6,
        assignedRequired: 6,
        assignmentPercent: 100,
        completionPercent: 100,
        deviationPercent: 0,
        revenue: "20 712 ₽",
        lostRevenue: "0 ₽" },

    { id: "a48",
        doctorId: "3",
        date: "24.02.2026",
        number: "№48", mkb: "I22.0",
        requiredServices: 5,
        assignedRequired: 2,
        assignmentPercent: 40,
        completionPercent: 50,
        deviationPercent: 80,
        revenue: "3 452 ₽",
        lostRevenue: "13 808 ₽" },

    { id: "a49",
        doctorId: "3",
        date: "24.02.2026",
        number: "№49", mkb: "I22.1",
        requiredServices: 6,
        assignedRequired: 4,
        assignmentPercent: 67,
        completionPercent: 50,
        deviationPercent: 67,
        revenue: "6 904 ₽",
        lostRevenue: "13 808 ₽" },

    { id: "a50",
        doctorId: "3",
        date: "24.02.2026",
        number: "№50", mkb: "I22.8",
        requiredServices: 7,
        assignedRequired: 7,
        assignmentPercent: 100,
        completionPercent: 100,
        deviationPercent: 0,
        revenue: "24 164 ₽",
        lostRevenue: "0 ₽" },

    { id: "a51",
        doctorId: "3",
        date: "25.02.2026",
        number: "№51", mkb: "I22.9",
        requiredServices: 6,
        assignedRequired: 1,
        assignmentPercent: 0,
        completionPercent: 0,
        deviationPercent: 100,
        revenue: "0 ₽",
        lostRevenue: "20 712 ₽" },

    { id: "a52",
        doctorId: "3",
        date: "25.02.2026",
        number: "№52", mkb: "I24.0",
        requiredServices: 6,
        assignedRequired: 3,
        assignmentPercent: 50,
        completionPercent: 100,
        deviationPercent: 50,
        revenue: "10 356 ₽",
        lostRevenue: "10 356 ₽" },

    { id: "a53",
        doctorId: "3",
        date: "25.02.2026",
        number: "№53", mkb: "I24.8",
        requiredServices: 7,
        assignedRequired: 5,
        assignmentPercent: 71,
        completionPercent: 0,
        deviationPercent: 100,
        revenue: "0 ₽",
        lostRevenue: "24 164 ₽" },

    { id: "a54",
        doctorId: "3",
        date: "25.02.2026",
        number: "№54", mkb: "I24.9",
        requiredServices: 5,
        assignedRequired: 5,
        assignmentPercent: 100,
        completionPercent: 80,
        deviationPercent: 20,
        revenue: "13 808 ₽",
        lostRevenue: "3 452 ₽" },

    { id: "a55",
        doctorId: "3",
        date: "25.02.2026",
        number: "№55", mkb: "I21.1",
        requiredServices: 6,
        assignedRequired: 2,
        assignmentPercent: 33,
        completionPercent: 100,
        deviationPercent: 67,
        revenue: "6 904 ₽",
        lostRevenue: "13 808 ₽" },

    { id: "a56",
        doctorId: "3",
        date: "26.02.2026",
        number: "№56", mkb: "I21.2",
        requiredServices: 6,
        assignedRequired: 6,
        assignmentPercent: 100,
        completionPercent: 17,
        deviationPercent: 83,
        revenue: "3 452 ₽",
        lostRevenue: "17 260 ₽" },

    { id: "a57",
        doctorId: "3",
        date: "26.02.2026",
        number: "№57", mkb: "I21.3",
        requiredServices: 7,
        assignedRequired: 4,
        assignmentPercent: 57,
        completionPercent: 100,
        deviationPercent: 43,
        revenue: "13 808 ₽",
        lostRevenue: "10 356 ₽" },

    { id: "a58",
        doctorId: "3",
        date: "26.02.2026",
        number: "№58", mkb: "I21.9",
        requiredServices: 6,
        assignedRequired: 3,
        assignmentPercent: 50,
        completionPercent: 0,
        deviationPercent: 100,
        revenue: "0 ₽",
        lostRevenue: "20 712 ₽" },

    { id: "a59",
        doctorId: "3",
        date: "26.02.2026",
        number: "№59", mkb: "I22.0",
        requiredServices: 5,
        assignedRequired: 1,
        assignmentPercent: 20,
        completionPercent: 100,
        deviationPercent: 80,
        revenue: "3 452 ₽",
        lostRevenue: "13 808 ₽" },

    { id: "a60",
        doctorId: "3",
        date: "26.02.2026",
        number: "№60", mkb: "I22.1",
        requiredServices: 6,
        assignedRequired: 5,
        assignmentPercent: 83,
        completionPercent: 100,
        deviationPercent: 17,
        revenue: "17 260 ₽",
        lostRevenue: "3 452 ₽" },

    { id: "a61",
        doctorId: "3",
        date: "27.02.2026",
        number: "№61", mkb: "I22.8",
        requiredServices: 7,
        assignedRequired: 6,
        assignmentPercent: 86,
        completionPercent: 50,
        deviationPercent: 57,
        revenue: "10 356 ₽",
        lostRevenue: "13 808 ₽" },

    { id: "a62",
        doctorId: "3",
        date: "27.02.2026",
        number: "№62", mkb: "I22.9",
        requiredServices: 6,
        assignedRequired: 4,
        assignmentPercent: 67,
        completionPercent: 100,
        deviationPercent: 33,
        revenue: "13 808 ₽",
        lostRevenue: "6 904 ₽" },

    { id: "a63",
        doctorId: "3",
        date: "27.02.2026",
        number: "№63", mkb: "I24.0",
        requiredServices: 6,
        assignedRequired: 2,
        assignmentPercent: 33,
        completionPercent: 0,
        deviationPercent: 100,
        revenue: "0 ₽",
        lostRevenue: "20 712 ₽" },

    { id: "a64",
        doctorId: "3",
        date: "27.02.2026",
        number: "№64", mkb: "I24.8",
        requiredServices: 7,
        assignedRequired: 7,
        assignmentPercent: 100,
        completionPercent: 100,
        deviationPercent: 0,
        revenue: "24 164 ₽",
        lostRevenue: "0 ₽" },

    { id: "a65",
        doctorId: "3",
        date: "27.02.2026",
        number: "№65", mkb: "I24.9",
        requiredServices: 5,
        assignedRequired: 3,
        assignmentPercent: 60,
        completionPercent: 33,
        deviationPercent: 80,
        revenue: "3 452 ₽",
        lostRevenue: "13 808 ₽" },

    { id: "a66",
        doctorId: "3",
        date: "27.02.2026",
        number: "№66", mkb: "I21.0",
        requiredServices: 6,
        assignedRequired: 5,
        assignmentPercent: 83,
        completionPercent: 100,
        deviationPercent: 17,
        revenue: "17 260 ₽",
        lostRevenue: "3 452 ₽" },

    { id: "a67",
        doctorId: "3",
        date: "28.02.2026",
        number: "№67", mkb: "I21.1",
        requiredServices: 5,
        assignedRequired: 2,
        assignmentPercent: 40,
        completionPercent: 100,
        deviationPercent: 60,
        revenue: "6 904 ₽",
        lostRevenue: "10 356 ₽" },

    { id: "a68",
        doctorId: "3",
        date: "28.02.2026",
        number: "№68", mkb: "I21.2",
        requiredServices: 6,
        assignedRequired: 6,
        assignmentPercent: 100,
        completionPercent: 0,
        deviationPercent: 100,
        revenue: "0 ₽",
        lostRevenue: "20 712 ₽" },

    { id: "a69",
        doctorId: "3",
        date: "28.02.2026",
        number: "№69", mkb: "I21.3",
        requiredServices: 7,
        assignedRequired: 3,
        assignmentPercent: 43,
        completionPercent: 100,
        deviationPercent: 57,
        revenue: "10 356 ₽",
        lostRevenue: "13 808 ₽" },

    { id: "a70",
        doctorId: "3",
        date: "28.02.2026",
        number: "№70", mkb: "I21.9",
        requiredServices: 6,
        assignedRequired: 4,
        assignmentPercent: 67,
        completionPercent: 100,
        deviationPercent: 33,
        revenue: "13 808 ₽",
        lostRevenue: "6 904 ₽" },

    { id: "a71",
        doctorId: "3",
        date: "28.02.2026",
        number: "№71", mkb: "I22.0",
        requiredServices: 5,
        assignedRequired: 1,
        assignmentPercent: 20,
        completionPercent: 100,
        deviationPercent: 80,
        revenue: "3 452 ₽",
        lostRevenue: "13 808 ₽" },

    { id: "a72",
        doctorId: "3",
        date: "28.02.2026",
        number: "№72", mkb: "I22.1",
        requiredServices: 6,
        assignedRequired: 5,
        assignmentPercent: 83,
        completionPercent: 100,
        deviationPercent: 17,
        revenue: "17 260 ₽",
        lostRevenue: "3 452 ₽" },

];

export async function GET(request: Request) {
    const { searchParams } = new URL(request.url);
    const doctorId = searchParams.get("doctorId");

    if (!doctorId) {
        return NextResponse.json(
            { error: "Missing doctorId parameter" },
            { status: 400 }
        );
    }

    const doctorAppointments = appointments
        .filter((a) => a.doctorId === doctorId)
        .map((a) => ({
            ...a,
            assignedTotal: a.assignedTotal ?? a.assignedRequired,
        }));

    return NextResponse.json(doctorAppointments);
}
