import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { Sidebar } from "@/components/Sidebar";
import { TopFilters } from "@/components/TopFilters";
import { FiltersProvider } from "@/context/FiltersContext";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${GeistSans.className} antialiased dark:bg-gray-950`}
        >
        <body className="min-h-screen flex bg-gray-50 dark:bg-gray-950">
        <Sidebar />

        <FiltersProvider>
            <div className="flex-1 flex flex-col">
                <TopFilters />
                <main className="flex-1 overflow-auto p-8">{children}</main>
            </div>
        </FiltersProvider>
        </body>
        </html>
    );
}
