import type { Metadata } from "next";
import "./globals.css";
import { GeistSans } from "geist/font/sans";
import { Sidebar } from "@/components/Sidebar";
import { FiltersProvider } from "@/context/FiltersContext";
import { ModeProvider } from "@/context/ModeContext";
import { TopFilters } from "@/components/TopFilters";
import { ConditionalDrawer } from "@/components/ConditionalDrawer";
import { InlineDrawerProvider } from "@/context/InlineDrawerContext"; // добавили

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ru" className={`${GeistSans.className} antialiased dark:bg-gray-950`}>
        <body className="h-screen flex overflow-hidden bg-gray-50 dark:bg-gray-950">
        <Sidebar />

        <FiltersProvider>
            <ModeProvider>
                <InlineDrawerProvider>
                    <ConditionalDrawer />

                    <div className="flex-1 flex flex-col min-w-0">
                        <TopFilters />
                        <main className="flex-1 overflow-y-auto overflow-x-hidden p-1 min-w-0 flex justify-center">
                            {children}
                        </main>
                    </div>

                </InlineDrawerProvider>
            </ModeProvider>
        </FiltersProvider>
        </body>
        </html>
    );
}
