import { NextResponse } from "next/server";

export async function GET() {
    const nosologies = [
        {
            id: "1",
            name: "Артериальная гипертензия у взрослых",
            appointments: 228,
            primaryAppointments: 96,
            repeatAppointments: 132,
            appointmentsWithoutServices: 16,
            oukr: 63,
            assignedOUKRPercent: 92,
            servicesCompletedPercent: 80,
            overKR: 3,
            totalServicesAssigned: 702,
            avgServicesPerVisit: 3.1,
            revenue: "616 000 ₽",
            avgCheck: "2 700 ₽",
            potentialRevenue: "648 000 ₽",
            lostOUKRRevenue: "32 000 ₽",
            lostOUKRPercent: 5,
        },
        {
            id: "2",
            name: "Хроническая сердечная недостаточность",
            appointments: 204,
            primaryAppointments: 68,
            repeatAppointments: 136,
            appointmentsWithoutServices: 11,
            oukr: 60,
            assignedOUKRPercent: 95,
            servicesCompletedPercent: 82,
            overKR: 2,
            totalServicesAssigned: 678,
            avgServicesPerVisit: 3.3,
            revenue: "663 000 ₽",
            avgCheck: "3 250 ₽",
            potentialRevenue: "691 000 ₽",
            lostOUKRRevenue: "28 000 ₽",
            lostOUKRPercent: 4,
        },
        {
            id: "3",
            name: "Внебольничная пневмония у взрослых",
            appointments: 178,
            primaryAppointments: 59,
            repeatAppointments: 119,
            appointmentsWithoutServices: 15,
            oukr: 54,
            assignedOUKRPercent: 91,
            servicesCompletedPercent: 78,
            overKR: 2,
            totalServicesAssigned: 552,
            avgServicesPerVisit: 3.1,
            revenue: "534 000 ₽",
            avgCheck: "3 000 ₽",
            potentialRevenue: "568 000 ₽",
                lostOUKRRevenue: "34 000 ₽",
            lostOUKRPercent: 6,
        },
        {
            id: "4",
            name: "Хроническая обструктивная болезнь легких",
                appointments: 156,
            primaryAppointments: 47,
            repeatAppointments: 109,
            appointmentsWithoutServices: 10,
            oukr: 48,
            assignedOUKRPercent: 94,
            servicesCompletedPercent: 81,
            overKR: 1,
            totalServicesAssigned: 515,
            avgServicesPerVisit: 3.3,
            revenue: "514 800 ₽",
            avgCheck: "3 300 ₽",
            potentialRevenue: "536 000 ₽",
            lostOUKRRevenue: "21 200 ₽",
            lostOUKRPercent: 4,
        },
        {
            id: "5",
            name: "Ишемическая болезнь сердца",
                appointments: 126,
            primaryAppointments: 38,
            repeatAppointments: 88,
            appointmentsWithoutServices: 9,
            oukr: 37,
            assignedOUKRPercent: 90,
            servicesCompletedPercent: 77,
            overKR: 2,
                totalServicesAssigned: 390,
            avgServicesPerVisit: 3.1,
            revenue: "365 400 ₽",
            avgCheck: "2 900 ₽",
            potentialRevenue: "390 000 ₽",
                lostOUKRRevenue: "24 600 ₽",
            lostOUKRPercent: 6,
        },
        {
            id: "6",
            name: "Острый коронарный синдром без подъёма сегмента ST",
            appointments: 126,
            primaryAppointments: 38,
            repeatAppointments: 88,
            appointmentsWithoutServices: 9,
            oukr: 37,
            assignedOUKRPercent: 90,
            servicesCompletedPercent: 77,
            overKR: 2,
            totalServicesAssigned: 390,
            avgServicesPerVisit: 3.1,
            revenue: "365 400 ₽",
            avgCheck: "2 900 ₽",
            potentialRevenue: "390 000 ₽",
            lostOUKRRevenue: "24 600 ₽",
            lostOUKRPercent: 6,
        },
        {
            id: "7",
            name: "Инфаркт миокарда с подъёмом сегмента ST",
            appointments: 126,
            primaryAppointments: 38,
            repeatAppointments: 88,
            appointmentsWithoutServices: 9,
            oukr: 37,
            assignedOUKRPercent: 90,
            servicesCompletedPercent: 77,
            overKR: 2,
            totalServicesAssigned: 390,
            avgServicesPerVisit: 3.1,
            revenue: "365 400 ₽",
            avgCheck: "2 900 ₽",
            potentialRevenue: "390 000 ₽",
            lostOUKRRevenue: "24 600 ₽",
            lostOUKRPercent: 6,
        },
        {
            id: "8",
            name: "Сахарный диабет 1 типа у взрослых",
            appointments: 126,
            primaryAppointments: 38,
            repeatAppointments: 88,
            appointmentsWithoutServices: 9,
            oukr: 37,
            assignedOUKRPercent: 90,
            servicesCompletedPercent: 77,
            overKR: 2,
            totalServicesAssigned: 390,
            avgServicesPerVisit: 3.1,
            revenue: "365 400 ₽",
            avgCheck: "2 900 ₽",
            potentialRevenue: "390 000 ₽",
            lostOUKRRevenue: "24 600 ₽",
            lostOUKRPercent: 6,
        },
        {
            id: "9",
            name: "Сахарный диабет 2 типа у взрослых",
            appointments: 126,
            primaryAppointments: 38,
            repeatAppointments: 88,
            appointmentsWithoutServices: 9,
            oukr: 37,
            assignedOUKRPercent: 90,
            servicesCompletedPercent: 77,
            overKR: 2,
            totalServicesAssigned: 390,
            avgServicesPerVisit: 3.1,
            revenue: "365 400 ₽",
            avgCheck: "2 900 ₽",
            potentialRevenue: "390 000 ₽",
            lostOUKRRevenue: "24 600 ₽",
            lostOUKRPercent: 6,
        },
        {
            id: "10",
            name: "Ожирение у взрослых",
            appointments: 126,
            primaryAppointments: 38,
            repeatAppointments: 88,
            appointmentsWithoutServices: 9,
            oukr: 37,
            assignedOUKRPercent: 90,
            servicesCompletedPercent: 77,
            overKR: 2,
            totalServicesAssigned: 390,
            avgServicesPerVisit: 3.1,
            revenue: "365 400 ₽",
            avgCheck: "2 900 ₽",
            potentialRevenue: "390 000 ₽",
            lostOUKRRevenue: "24 600 ₽",
            lostOUKRPercent: 6,
        },
        {
            id: "11",
            name: "Бронхиальная астма",
            appointments: 126,
            primaryAppointments: 38,
            repeatAppointments: 88,
            appointmentsWithoutServices: 9,
            oukr: 37,
            assignedOUKRPercent: 90,
            servicesCompletedPercent: 77,
            overKR: 2,
            totalServicesAssigned: 390,
            avgServicesPerVisit: 3.1,
            revenue: "365 400 ₽",
            avgCheck: "2 900 ₽",
            potentialRevenue: "390 000 ₽",
            lostOUKRRevenue: "24 600 ₽",
            lostOUKRPercent: 6,
        },
        {
            id: "12",
            name: "Аллергический ринит",
            appointments: 126,
            primaryAppointments: 38,
            repeatAppointments: 88,
            appointmentsWithoutServices: 9,
            oukr: 37,
            assignedOUKRPercent: 90,
            servicesCompletedPercent: 77,
            overKR: 2,
            totalServicesAssigned: 390,
            avgServicesPerVisit: 3.1,
            revenue: "365 400 ₽",
            avgCheck: "2 900 ₽",
            potentialRevenue: "390 000 ₽",
            lostOUKRRevenue: "24 600 ₽",
            lostOUKRPercent: 6,
        },
];

    return NextResponse.json(nosologies);
}
