import { NextResponse } from "next/server";

export async function GET() {
    const nosologies = [
        {
            id: "1",
            name: "ОРВИ",
            appointments: 120,
            primaryAppointments: 45,
            repeatAppointments: 75,
            appointmentsWithoutServices: 10,
            oukr: 50,
            assignedOUKRPercent: 90,
            servicesCompletedPercent: 85,
            overKR: 5,
            totalServicesAssigned: 55,
            avgServicesPerVisit: 3.2,
            revenue: "1 250 000 ₽",
            avgCheck: "2 500 ₽",
            potentialRevenue: "1 400 000 ₽",
            lostOUKRRevenue: "150 000 ₽",
            lostOUKRPercent: 10,
        },
        {
            id: "2",
            name: "Бронхит",
            appointments: 95,
            primaryAppointments: 30,
            repeatAppointments: 65,
            appointmentsWithoutServices: 5,
            oukr: 45,
            assignedOUKRPercent: 85,
            servicesCompletedPercent: 80,
            overKR: 7,
            totalServicesAssigned: 52,
            avgServicesPerVisit: 3.1,
            revenue: "980 000 ₽",
            avgCheck: "2 600 ₽",
            potentialRevenue: "1 050 000 ₽",
            lostOUKRRevenue: "70 000 ₽",
            lostOUKRPercent: 7,
        },
        {
            id: "3",
            name: "Пневмония",
            appointments: 60,
            primaryAppointments: 20,
            repeatAppointments: 40,
            appointmentsWithoutServices: 6,
            oukr: 30,
            assignedOUKRPercent: 88,
            servicesCompletedPercent: 82,
            overKR: 3,
            totalServicesAssigned: 33,
            avgServicesPerVisit: 3.4,
            revenue: "1 150 000 ₽",
            avgCheck: "3 000 ₽",
            potentialRevenue: "1 300 000 ₽",
            lostOUKRRevenue: "130 000 ₽",
            lostOUKRPercent: 10,
        },
        {
            id: "4",
            name: "Отит",
            appointments: 45,
            primaryAppointments: 15,
            repeatAppointments: 30,
            appointmentsWithoutServices: 3,
            oukr: 25,
            assignedOUKRPercent: 92,
            servicesCompletedPercent: 85,
            overKR: 2,
            totalServicesAssigned: 27,
            avgServicesPerVisit: 3.2,
            revenue: "780 000 ₽",
            avgCheck: "2 800 ₽",
            potentialRevenue: "850 000 ₽",
            lostOUKRRevenue: "70 000 ₽",
            lostOUKRPercent: 8,
        },
        {
            id: "5",
            name: "Тонзиллит",
            appointments: 80,
            primaryAppointments: 35,
            repeatAppointments: 45,
            appointmentsWithoutServices: 5,
            oukr: 40,
            assignedOUKRPercent: 87,
            servicesCompletedPercent: 83,
            overKR: 4,
            totalServicesAssigned: 44,
            avgServicesPerVisit: 3.3,
            revenue: "1 000 000 ₽",
            avgCheck: "2 900 ₽",
            potentialRevenue: "1 150 000 ₽",
            lostOUKRRevenue: "150 000 ₽",
            lostOUKRPercent: 13,
        },
    ];

    return NextResponse.json(nosologies);
}
